books = [
    {
        'book':'Genesis',
        'img':'static/images/icons/genesis.png'
    },
    {
        'book':'Exodus',
        'img':'static/images/icons/exodus.png'
    },
    {
        'book':'Leviticus',
        'img':'static/images/icons/leviticus.png'
    },
    {
        'book':'Numbers',
        'img':'static/images/icons/numbers.png'
    },
    {
        'book':'Deuteronomy',
        'img':'static/images/icons/deuteronomy.png'
    },
    {
        'book':'Joshua',
        'img':'static/images/icons/joshua.png'
    },
    {
        'book':'Judges',
        'img':'static/images/icons/joshua.png'
    },
    {
        'book':'Ruth',
        'img':'static/images/icons/ruth.png'
    },
    {
        'book':'1 Samuel',
        'img':'static/images/icons/samuel.png'
    },
    {
        'book':'2 Samuel',
        'img':'static/images/icons/samuel.png'
    },
    {
        'book':'1 Kings',
        'img':'static/images/icons/kings.png'
    },
    {
        'book':'2 Kings',
        'img':'static/images/icons/kings.png'
    },
    {
        'book':'1 Chronicles',
        'img':'static/images/icons/chronicles.png'
    },
    {
        'book':'2 Chronicles',
        'img':'static/images/icons/chronicles.png'
    },
    {
        'book':'Ezra',
        'img':'static/images/icons/ezra.png'
    },
    {
        'book':'Nehemiah',
        'img':'static/images/icons/nehemiah.png'
    },
    {
        'book':'Esther',
        'img':'static/images/icons/esther.png'
    },
    {
        'book':'Job',
        'img':'static/images/icons/job.png'
    },
    {
        'book':'Psalms',
        'img':'static/images/icons/psalms.png'
    },
    {
        'book':'Proverbs',
        'img':'static/images/icons/proverbs.png'
    },
    {
        'book':'Ecclesiastes',
        'img':'static/images/icons/ecclesiastes.png'
    },
    {
        'book':'Song of Solomon',
        'img':'static/images/icons/song-of-solomon.png'
    },
    {
        'book':'Isaiah',
        'img':'static/images/icons/isaiah.png'
    },
    {
        'book':'Jeremiah',
        'img':'static/images/icons/jeremiah.png'
    },
    {
        'book':'Lamentations',
        'img':'static/images/icons/lamentations.png'
    },
    {
        'book':'Ezekiel',
        'img':'static/images/icons/ezekiel.png'
    },
    {
        'book':'Daniel',
        'img':'static/images/icons/daniel.png'
    },
    {
        'book':'Hosea',
        'img':'static/images/icons/hosea.png'
    },
    {
        'book':'Joel',
        'img':'static/images/icons/joel.png'
    },
    {
        'book':'Amos',
        'img':'static/images/icons/amos.png'
    },
    {
        'book':'Obadiah',
        'img':'static/images/icons/obadiah.png'
    },
    {
        'book':'Jonah',
        'img':'static/images/icons/jonah.png'
    },
    {
        'book':'Micah',
        'img':'static/images/icons/micah.png'
    },
    {
        'book':'Nahum',
        'img':'static/images/icons/nahum.png'
    },
    {
        'book':'Habakkuk',
        'img':'static/images/icons/habakkuk.png'
    },
    {
        'book':'Zephaniah',
        'img':'static/images/icons/zephaniah.png'
    },
    {
        'book':'Haggai',
        'img':'static/images/icons/haggai.png'
    },
    {
        'book':'Zechariah',
        'img':'static/images/icons/zechariah.png'
    },
    {
        'book':'Malachi',
        'img':'static/images/icons/malachi.png'
    },
    {
        'book':'Matthew',
        'img':'static/images/icons/matthew.png'
    },
    {
        'book':'Mark',
        'img':'static/images/icons/mark.png'
    },
    {
        'book':'Luke',
        'img':'static/images/icons/luke.png'
    },
    {
        'book':'John',
        'img':'static/images/icons/john.png'
    },
    {
        'book':'Acts',
        'img':'static/images/icons/acts.png'
    },
    {
        'book':'Romans',
        'img':'static/images/icons/romans.png'
    },
    {
        'book':'1 Corinthians',
        'img':'static/images/icons/1-corinthians.png'
    },
    {
        'book':'2 Corinthians',
        'img':'static/images/icons/2-corinthians.png'
    },
    {
        'book':'Galatians',
        'img':'static/images/icons/galatians.png'
    },
    {
        'book':'Ephesians',
        'img':'static/images/icons/ephesians.png'
    },
    {
        'book':'Philippians',
        'img':'static/images/icons/philippians.png'
    },
    {
        'book':'Colossians',
        'img':'static/images/icons/colossians.png'
    },
    {
        'book':'1 Thessalonians',
        'img':'static/images/icons/1-thessalonians.png'
    },
    {
        'book':'2 Thessalonians',
        'img':'static/images/icons/2-thessalonians.png'
    },
    {
        'book':'1 Timothy',
        'img':'static/images/icons/1-timothy.png'
    },
    {
        'book':'2 Timothy',
        'img':'static/images/icons/2-timothy.png'
    },
    {
        'book':'Titus',
        'img':'static/images/icons/titus.png'
    },
    {
        'book':'Philemon',
        'img':'static/images/icons/philemon.png'
    },
    {
        'book':'Hebrews',
        'img':'static/images/icons/hebrews.png'
    },
    {
        'book':'James',
        'img':'static/images/icons/james.png'
    },
    {
        'book':'1 Peter',
        'img':'static/images/icons/1-peter.png'
    },
    {
        'book':'2 Peter',
        'img':'static/images/icons/2-peter.png'
    },
    {
        'book':'1 John',
        'img':'static/images/icons/1-john.png'
    },
    {
        'book':'2 John',
        'img':'static/images/icons/2-john.png'
    },
    {
        'book':'3 John',
        'img':'static/images/icons/3-john.png'
    },
    {
        'book':'Jude',
        'img':'static/images/icons/jude.png'
    },
    {
        'book':'Revelation',
        'img':'static/images/icons/revelation.png'
    }
]